"""Build a self-contained HTML compliance report."""

from __future__ import annotations

import re
from datetime import datetime

from core.models import CheckResult, ComplianceReport, Recommendation, Severity

RULES_BASE_URL = "https://www.ndcourts.gov/legal-resources/rules/ndrappp"
NDRCT_RULES_BASE_URL = "https://www.ndcourts.gov/legal-resources/rules/ndrct"


def build_html_report(report: ComplianceReport, version_stamp: str = "", model: str = "") -> str:
    """Generate a self-contained HTML report with inline CSS.

    ``model`` is the Claude model identifier (supplied by the runtime/caller),
    recorded in the footer for provenance and later comparison as the model and
    the skill change. The skill version (``version_stamp``) and the generation
    date (the Date metadata row) are already sourced deterministically.
    """
    rec = report.recommendation
    banner_color = {
        Recommendation.ACCEPT: "#22863a",
        Recommendation.CORRECTION_LETTER: "#b08800",
        Recommendation.REJECT: "#cb2431",
    }[rec]
    banner_bg = {
        Recommendation.ACCEPT: "#dcffe4",
        Recommendation.CORRECTION_LETTER: "#fff8c5",
        Recommendation.REJECT: "#ffeef0",
    }[rec]
    banner_label = {
        Recommendation.ACCEPT: "ACCEPT",
        Recommendation.CORRECTION_LETTER: "CORRECTION LETTER",
        Recommendation.REJECT: "REJECT",
    }[rec]

    failed_html = _render_check_group(report.reject_failures, "Critical — Reject", "#cb2431")
    failed_html += _render_check_group(report.correction_failures, "Correction Required", "#b08800")
    failed_html += _render_check_group(report.note_failures, "Advisory Notes", "#6a737d")

    passed_html = _render_checks_table(report.passed_checks, passed=True)
    na_html = _render_checks_table(report.inapplicable_checks, passed=True)

    meta = report.metadata
    brief_type_label = meta.brief_type.value.replace("_", " ").title() if meta else "Unknown"

    # Build descriptive header
    title_line = "Appellate Brief Compliance Report"
    if report.case_title:
        title_line = f"{_esc(report.case_title)}"
    subtitle_parts = []
    if report.case_number:
        subtitle_parts.append(f"No. {_esc(report.case_number)}")
    if report.brief_label:
        subtitle_parts.append(_esc(report.brief_label))
    elif brief_type_label != "Unknown":
        subtitle_parts.append(f"{brief_type_label} Brief")
    subtitle_line = " — ".join(subtitle_parts) if subtitle_parts else "North Dakota Rules of Appellate Procedure"

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Compliance Report — {_esc(report.case_title) if report.case_title else report.report_id}</title>
<style>
{_css()}
</style>
</head>
<body>
<div class="container">
  <header>
    <p class="report-type">Brief Compliance Report</p>
    <h1>{title_line}</h1>
    <p class="subtitle">{subtitle_line}</p>
  </header>

  <div class="banner" style="background:{banner_bg}; border-color:{banner_color}; color:{banner_color};">
    <span class="rec-label">Recommended Action:</span>
    <span class="rec-value">{banner_label}</span>
  </div>

  <section class="meta">
    <table>
      <tr><td class="meta-label">Report ID</td><td>{report.report_id}</td></tr>
      <tr><td class="meta-label">Brief Type</td><td>{brief_type_label}</td></tr>
      <tr><td class="meta-label">Pages (body)</td><td>{meta.body_pages if meta else '—'}</td></tr>
      <tr><td class="meta-label">Pages (total)</td><td>{meta.total_pages if meta else '—'}</td></tr>
      <tr><td class="meta-label">Word Count</td><td>{meta.word_count if meta else '—'}</td></tr>
      <tr><td class="meta-label">Date</td><td>{datetime.now().strftime('%B %d, %Y %I:%M %p')}</td></tr>
    </table>
  </section>

  {f'<section class="reasoning"><h2>Analysis Summary</h2><p>{_esc(report.claude_reasoning)}</p></section>' if report.claude_reasoning else ''}

  <section class="results">
    <h2>Failed Checks ({len(report.failed_checks)})</h2>
    {failed_html if report.failed_checks else '<p class="none">No failed checks.</p>'}
  </section>

  <section class="results">
    <details>
      <summary><h2 style="display:inline;">Passed Checks ({len(report.passed_checks)})</h2></summary>
      {passed_html if report.passed_checks else '<p class="none">—</p>'}
    </details>
  </section>

  {f'''<section class="results">
    <details>
      <summary><h2 style="display:inline;">Not Applicable / Not Determined ({len(report.inapplicable_checks)})</h2></summary>
      {na_html}
    </details>
  </section>''' if report.inapplicable_checks else ''}
  {_render_citation_review(report)}

  <footer>
    <p>Generated by JetBriefCheck{f' {_esc(version_stamp)}' if version_stamp else ''}{f' using {_esc(model)}' if model else ''}</p>
    <p class="engine-note">Mechanical checks: {'PyMuPDF' if report.pymupdf_used else 'Fallback (PyMuPDF unavailable — mechanical checks skipped)'}</p>
  </footer>
</div>
</body>
</html>"""


def _render_check_group(checks: list[CheckResult], title: str, color: str) -> str:
    if not checks:
        return ""
    rows = ""
    for c in checks:
        detail = f'<div class="detail">{_esc(c.details)}</div>' if c.details else ""
        pages_html = ""
        if c.pages:
            page_tags = " ".join(f'<span class="page-badge">p.{p}</span>' for p in c.pages)
            pages_html = f'<div class="check-pages">Pages: {page_tags}</div>'
        rows += f"""<div class="check-card failed" style="border-left-color:{color};">
  <div class="check-header">
    <span class="check-id">{c.check_id}</span>
    <span class="check-name">{_esc(c.name)}</span>
    <span class="check-rule">{_rule_link(c.rule)}</span>
    <span class="severity severity-{c.severity.value}">{c.severity.value.upper()}</span>
  </div>
  <div class="check-msg">{_esc(c.message)}</div>
  {pages_html}
  {detail}
</div>
"""
    return f'<h3 style="color:{color};">{title}</h3>\n{rows}'


def _render_citation_review(report: ComplianceReport) -> str:
    """Render the citation-grounding section.

    Kept visually and structurally apart from the compliance findings. Rule
    compliance and citation accuracy are different questions, and only the
    first bears on whether the clerk accepts the brief. The banner says so
    outright, so a reader skimming headings cannot mistake a citation flag
    for a filing defect.
    """
    review = report.citation_review
    if review is None:
        return ""

    if not review.ndlaw_available:
        body = f'<p class="none">{_esc(review.coverage_line)}</p>'
    else:
        flagged = review.flagged
        if flagged:
            rows = ""
            for f in flagged:
                where = f" (brief ¶ {f.brief_paragraph})" if f.brief_paragraph else ""
                pin = f", ¶ {_esc(f.pinpoint)}" if f.pinpoint else ""
                bits = []
                if f.exists == "not_found":
                    bits.append("citation not found")
                if f.name_drifted:
                    bits.append(
                        f"brief names it {_esc(f.antecedent_name or '?')}; "
                        f"the reporter shows {_esc(f.canonical_name or '?')}")
                if f.quotation_result in ("altered", "not_found"):
                    bits.append(f"quotation {_esc(f.quotation_result).replace('_', ' ')}")
                rows += f"""<div class="cite-flag">
  <p class="cite-head"><strong>{_esc(f.cite)}{pin}</strong>{_esc(where)} — {"; ".join(bits)}</p>
  {f'<p class="cite-prop"><em>Brief states:</em> {_esc(f.proposition)}</p>' if f.proposition else ''}
  {f'<p class="cite-quote"><em>Brief quotes:</em> &ldquo;{_esc(f.quotation)}&rdquo;</p>' if f.quotation else ''}
  {f'<p class="cite-passage"><em>Authority says:</em> {_esc(f.retrieved_excerpt)}</p>' if f.retrieved_excerpt else ''}
  {f'<p class="cite-reason">{_esc(f.reason)}</p>' if f.reason else ''}
</div>
"""
            body = rows
        else:
            body = ('<p class="none">No citation was flagged. '
                    'See the coverage line above for what was checked.</p>')

    return f"""
  <section class="results citation-review">
    <h2>Citation Review ({len(review.flagged) if review.ndlaw_available else 0})</h2>
    <p class="advisory-banner">Advisory only — not part of the compliance
    determination. This section checks that each authority exists, that it is
    the case the brief names, and that quoted matter is accurate. It does
    <strong>not</strong> assess whether an authority supports the proposition
    it is cited for — that judgment is for chambers. Nothing here affects the
    recommended action above.</p>
    <p class="coverage">{_esc(review.coverage_line)}</p>
    {body}
  </section>"""


def _render_checks_table(checks: list[CheckResult], passed: bool = True) -> str:
    if not checks:
        return ""
    rows = ""
    for c in checks:
        pages_cell = ""
        if c.pages:
            pages_cell = ", ".join(str(p) for p in c.pages)
        rows += f"""<tr>
  <td class="check-id-cell">{c.check_id}</td>
  <td>{_esc(c.name)}</td>
  <td>{_rule_link(c.rule)}</td>
  <td>{_esc(c.message)}</td>
  <td class="pages-cell">{pages_cell}</td>
</tr>
"""
    return f"""<table class="checks-table">
<thead><tr><th>ID</th><th>Check</th><th>Rule</th><th>Result</th><th>Pages</th></tr></thead>
<tbody>{rows}</tbody>
</table>"""


def _esc(text: str) -> str:
    """Escape HTML special characters."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def _rule_link(rule_str: str) -> str:
    """Convert a rule citation like '32(a)(1)' into an HTML hyperlink.

    Maps to the appropriate ndcourts.gov URL:
    - N.D.R.Ct. rules → /legal-resources/rules/ndrct/{rule_number with hyphens}
    - N.D.R.App.P. rules → /legal-resources/rules/ndrappp/{rule_number}
    Handles compound citations like '28(h)/34'.
    """
    parts = rule_str.split("/")
    links = []
    for part in parts:
        part = part.strip()
        # Check for N.D.R.Ct. prefix (e.g., "N.D.R.Ct. 11.6(b)")
        ndrct_match = re.match(r"N\.D\.R\.Ct\.\s*([\d.]+)", part)
        if ndrct_match:
            rule_num = ndrct_match.group(1)
            # ndcourts.gov uses hyphens for dots in N.D.R.Ct. URLs (e.g., 3-4, 11-6)
            url_num = rule_num.replace(".", "-")
            url = f"{NDRCT_RULES_BASE_URL}/{url_num}"
            links.append(f'<a href="{url}" target="_blank" class="rule-link">N.D.R.Ct. {part[ndrct_match.start(1):]}</a>')
            continue
        # Extract the base rule number (digits/dots before any parenthetical)
        match = re.match(r"([\d.]+)", part)
        if match:
            rule_num = match.group(1)
            # Determine base URL: rule numbers with dots (like 3.4, 11.6) are N.D.R.Ct.
            if "." in rule_num:
                url_num = rule_num.replace(".", "-")
                url = f"{NDRCT_RULES_BASE_URL}/{url_num}"
            else:
                url = f"{RULES_BASE_URL}/{rule_num}"
            links.append(f'<a href="{url}" target="_blank" class="rule-link">Rule {part}</a>')
        else:
            links.append(f"Rule {_esc(part)}")
    return " / ".join(links)


def _css() -> str:
    return """
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: 'Segoe UI', system-ui, -apple-system, sans-serif; background: #f6f8fa; color: #24292e; line-height: 1.5; }
.container { max-width: 900px; margin: 2rem auto; padding: 0 1rem; }
header { text-align: center; margin-bottom: 1.5rem; }
header .report-type { color: #586069; font-size: 0.85rem; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 0.25rem; }
header h1 { font-size: 1.6rem; font-weight: 600; }
header .subtitle { color: #586069; font-size: 0.95rem; }
.banner { border: 2px solid; border-radius: 8px; padding: 1rem 1.5rem; margin-bottom: 1.5rem; display: flex; align-items: center; gap: 0.75rem; }
.rec-label { font-weight: 500; font-size: 1rem; }
.rec-value { font-weight: 700; font-size: 1.3rem; }
.meta { margin-bottom: 1.5rem; }
.meta table { width: 100%; border-collapse: collapse; }
.meta td { padding: 0.35rem 0.75rem; border-bottom: 1px solid #e1e4e8; }
.meta-label { font-weight: 600; width: 140px; color: #586069; }
.reasoning { background: #f1f8ff; border: 1px solid #c8e1ff; border-radius: 6px; padding: 1rem; margin-bottom: 1.5rem; }
.reasoning h2 { font-size: 1rem; margin-bottom: 0.5rem; }
.reasoning p { font-size: 0.95rem; }
.results { margin-bottom: 1.5rem; }
.results h2 { font-size: 1.15rem; margin-bottom: 0.75rem; }
.results h3 { font-size: 1rem; margin: 0.75rem 0 0.5rem; }
.check-card { border-left: 4px solid; border-radius: 4px; background: #fff; padding: 0.75rem 1rem; margin-bottom: 0.5rem; box-shadow: 0 1px 3px rgba(0,0,0,0.04); }
.check-header { display: flex; align-items: center; gap: 0.5rem; flex-wrap: wrap; }
.check-id { font-family: monospace; font-size: 0.85rem; background: #f1f1f1; padding: 0.1rem 0.4rem; border-radius: 3px; }
.check-name { font-weight: 600; }
.check-rule { font-size: 0.85rem; }
.rule-link { color: #0366d6; text-decoration: none; }
.rule-link:hover { text-decoration: underline; }
.severity { font-size: 0.75rem; font-weight: 700; padding: 0.15rem 0.5rem; border-radius: 3px; text-transform: uppercase; margin-left: auto; }
.severity-reject { background: #ffeef0; color: #cb2431; }
.severity-correction { background: #fff8c5; color: #735c0f; }
.severity-note { background: #f1f1f1; color: #586069; }
.check-msg { margin-top: 0.4rem; font-size: 0.93rem; }
.detail { margin-top: 0.3rem; font-size: 0.85rem; color: #586069; white-space: pre-line; }
.checks-table { width: 100%; border-collapse: collapse; font-size: 0.9rem; }
.checks-table th, .checks-table td { padding: 0.4rem 0.6rem; border-bottom: 1px solid #e1e4e8; text-align: left; }
.checks-table th { background: #f6f8fa; font-weight: 600; }
.check-id-cell { font-family: monospace; font-size: 0.85rem; }
.none { color: #586069; font-style: italic; }
details summary { cursor: pointer; }
details summary::-webkit-details-marker { display: none; }
details summary::before { content: '▶ '; font-size: 0.8rem; }
details[open] summary::before { content: '▼ '; }
.check-pages { margin-top: 0.3rem; font-size: 0.85rem; color: #586069; }
.page-badge { display: inline-block; background: #e1e4e8; color: #24292e; font-size: 0.78rem; font-family: monospace; padding: 0.1rem 0.35rem; border-radius: 3px; margin: 0 0.15rem; }
.pages-cell { font-family: monospace; font-size: 0.85rem; color: #586069; white-space: nowrap; }
footer { text-align: center; color: #586069; font-size: 0.85rem; padding: 1.5rem 0; border-top: 1px solid #e1e4e8; margin-top: 2rem; }
.engine-note { font-size: 0.8rem; margin-top: 0.25rem; }
@media print { .container { max-width: 100%; } .banner { border-width: 3px; } details { open: true; } details[open] summary { display: none; } }
@media (max-width: 600px) { .check-header { flex-direction: column; align-items: flex-start; } .severity { margin-left: 0; } }

.citation-review { border-left: 4px solid #6b5b95; background: #faf9fc; }
.citation-review h2 { color: #4a3f6b; }
.advisory-banner {
  background: #efe9f7; border: 1px solid #d6c9e8; border-radius: 4px;
  padding: 0.6em 0.9em; font-size: 0.92em; color: #4a3f6b; margin: 0.5em 0 1em;
}
.coverage { font-weight: 600; margin-bottom: 1em; }
.cite-flag {
  border: 1px solid #ddd; border-left: 3px solid #b8a6d9; border-radius: 4px;
  padding: 0.7em 1em; margin-bottom: 0.9em; background: #fff;
}
.cite-head { margin: 0 0 0.4em; }
.cite-prop, .cite-quote, .cite-passage, .cite-reason { margin: 0.3em 0; font-size: 0.94em; }
.cite-passage { color: #333; background: #f6f6f8; padding: 0.4em 0.6em; border-radius: 3px; }
.cite-reason { color: #555; font-style: italic; }
"""
